---
- name: install Ldap-master
  hosts: ldap_masters
  become: true
  roles:
    - ldap
  
  tasks:
    - name: copyover basic ldap-config
      debug:
        msg: dies ist erstmal nur ein test

    - name: Copyover helperscripts
      copy:
        src: files/scripts/
        dest: /opt/ldap/scripts

    - name: Copyover ldif-files
      copy:
        src: files/ldifs/
        dest: /opt/ldap/ldifs
    
    - name: change rootpassword to test123
      shell:
        cmd:  /usr/bin/ldapmodify -Q -Y EXTERNAL -H ldapi:/// -f /opt/ldap/ldifs/changeRootPass.ldif
